### ISSUE TITLE
Subject

### ISSUE THREAD

**Issue by LucasKuhn** [erick-medeiros/42sp-webserv#46]
# [Subject.pdf](https://cdn.intra.42.fr/pdf/pdf/84928/en.subject.pdf)

# Mandadory Part 

|**Program name**|webserv|
| - | - |
|**Turn in files**|Makefile, \*.{h, hpp}, \*.cpp, \*.tpp, \*.ipp, configuration files|
|**Makefile**|NAME, all, clean, fclean, re|
|**Arguments**|[A configuration file]|
|**External functs.**|<p>Everything in C++ 98.</p><p>execve, dup, dup2, pipe, strerror, gai\_strerror, errno, dup, dup2, fork, htons, htonl, ntohs, ntohl, select, poll, epoll (epoll\_create, epoll\_ctl, epoll\_wait), kqueue (kqueue, kevent), socket, accept, listen, send, recv, bind, connect, getaddrinfo, freeaddrinfo, setsockopt, getsockname, getprotobyname, fcntl, close, read, write, waitpid, kill, signal, access, stat, opendir, readdir and closedir.</p>|
|**Libft authorized**|n/a|
|**Description**|A HTTP server in C++ 98|

You must write a HTTP server in C++ 98. Your executable will be run as follows:

./webserv [configuration file]

# General rules
- [x] Your program should not crash in any circumstances (even when it runs out ofmemory), and should not quit unexpectedly.If it happens, your project will be considered non-functional and your grade will be0.
- [x] You have to turn in a Makefile which will compile your source files. It must notrelink.
- [x] Your Makefile must at least contain the rules:$(NAME), all, clean, fclean and re.
- [x] Compile your code with c++ and the flags -Wall -Wextra -Werror
- [x] Your code must comply with the C++ 98 standard. Then, it should still compileif you add the flag -std=c++98.
- [x] Try to always develop using the most C++ features you can (for example, choose<cstring> over <string.h>). You are allowed to use C functions, but always prefertheir C++ versions if possible.
- [x] Any external library and Boost libraries are forbidden.

# Requirements
- [x] Your program has to take a configuration file as argument, or use a default path.
- [x] You can’t execve another web server.
- [x] Your server must never block and the client can be bounced properly if necessary.
- [x] It must be non-blocking and use only 1 poll() (or equivalent) for all the I/Ooperations between the client and the server (listen included).
- [x] poll() (or equivalent) must check read and write at the same time.
- [x] You must never do a read or a write operation without going through poll() (orequivalent).
- [x] Checking the value of errno is strictly forbidden after a read or a write operation.
- [x] #53
- [x] You can use every macro and define like FD_SET, FD_CLR, FD_ISSET, FD_ZERO (understanding what and how they do it is very useful).
- [x] A request to your server should never hang forever.
- [x] Your server must be compatible with the web browser of your choice.
- [x] We will consider that NGINX is HTTP 1.1 compliant and may be used to compare headers and answer behaviors.
- [x] Your HTTP response status codes must be accurate.
- [x] You server must have default error pages if none are provided.
- [x] You can’t use fork for something else than CGI (like PHP, or Python, and so forth).
- [x] You must be able to serve a fully static website.
- [x] Clients must be able to upload files.
- [x] #54
- [x] Stress tests your server. It must stay available at all cost.
- [x] Your server must be able to listen to multiple ports (see Configuration file).

# Configuration file
In the configuration file, you should be able to:
- [x] Choose the port and host of each ’server’.
- [x] #48
- [x] The first server for a host:port will be the default for this host:port (that means it will answer to all the requests that don’t belong to an other server). 
- [x] Setup default error pages.
- [x] Limit client body size.
- [x] Setup routes with one or multiple of the following rules/configuration (routes wont be using regexp):
  - [x] Define a list of accepted HTTP methods for the route.
  - [x] #58
  - [x] #49
  - [x] Turn on or off directory listing.
  - [x] #50
  - [x] Execute CGI based on certain file extension (for example .php).
  - [x] Make it work with POST and GET methods.
  - [x] #51
    - [x] Do you wonder what a CGI is?
    - [x] Because you won’t call the CGI directly, use the full path as PATH_INFO.
    - [x] #52
    - [x] Same things for the output of the CGI. If no content_length is returned from the CGI, EOF will mark the end of the returned data.
    - [x] Your program should call the CGI with the file requested as first argument.
    - [x] The CGI should be run in the correct directory for relative path file access.
    - [x] Your server should work with one CGI (php-CGI, Python, and so forth).
- [x] You must provide some configuration files and default basic files to test and demonstrate every feature works during evaluation

# Bonus part
Here are the extra features you can add:
- [x] #61
- [x] Handle multiple CGI.

#
> Even if poll() is mentionned in the subject and the evaluation scale, you can use any equivalent such as select(), kqueue(), or epoll().

> Please read the RFC and do some tests with telnet and NGINX before starting this project. Even if you don’t have to implement all the RFC, reading it will help you develop the required features.

> Because you have to use non-blocking file descriptors, it is possible to use read/recv or write/send functions with no poll() (or equivalent), and your server wouldn’t be blocking. But it would consume more system resources. Thus, if you try to read/recv or write/send in any file descriptor without using poll() (or equivalent), your grade will be 0.

> You can get some inspiration from the ’server’ part of NGINX configuration file.

> If you’ve got a question about one behavior, you should compare your program behavior with NGINX’s. For example, check how does server_name work. We’ve shared with you a small tester. It’s not mandatory to pass it if everything works fine with your browser and tests, but it can help you hunt some bugs.

> The important thing is resilience. Your server should never die.

> Do not test with only one program. Write your tests with a more convenient language such as Python or Golang, and so forth. Even in C or C++ if you want to.

> The bonus part will only be assessed if the mandatory part is PERFECT. Perfect means the mandatory part has been integrally done and works without malfunctioning. If you have not passed ALL the mandatory requirements, your bonus part will not be evaluated at all.

**Comment by erick-medeiros** [comment]
good job
