### ISSUE TITLE
Use send() instead of write()

### ISSUE THREAD

**Issue by LucasKuhn** [erick-medeiros/42sp-webserv#7]
https://github.com/erick-medeiros/42sp-webserv/blob/711c56fa34d83380a6595154d0643b426c12cae8/src/Webserv.cpp#L96

Mentioned on Beej guide that send() is better:
https://beej.us/guide/bgnet/html/split/what-is-a-socket.html#what-is-a-socket

**Comment by ichmi** [comment]
Na minha branch `feat/request-parser` ja fiz essas alteracoes das funcoes `read/write` para `send/recv`. 👍🏻
